class AS5600Constants:
    POWER_MODE_NORM = 0
    POWER_MODE_LPM1 = 1
    POWER_MODE_LPM2 = 2
    POWER_MODE_LPM3 = 3

    HYSTERESIS_OFF = 0
    HYSTERESIS_1LSB = 1
    HYSTERESIS_2LSB = 2
    HYSTERESIS_3LSB = 3

    OUTPUT_STAGE_ANALOG_FULL = 0
    OUTPUT_STAGE_ANALOG_REDUCED = 1
    OUTPUT_STAGE_DIGITAL_PWM = 2

    SLOW_FILTER_16X = 0
    SLOW_FILTER_8X = 1
    SLOW_FILTER_4X = 2
    SLOW_FILTER_2X = 3

    FAST_FILTER_THRESHOLD_SLOW = 0
    FAST_FILTER_THRESHOLD_6LSB = 1
    FAST_FILTER_THRESHOLD_7LSB = 2
    FAST_FILTER_THRESHOLD_9LSB = 3
    FAST_FILTER_THRESHOLD_18LSB = 4
    FAST_FILTER_THRESHOLD_21LSB = 5
    FAST_FILTER_THRESHOLD_24LSB = 6
    FAST_FILTER_THRESHOLD_10LSB = 7

    _ZMCOAddress = 0x00
    _ZPOSAddressMSB = 0x01
    _ZPOSAddressLSB = 0x02
    _MPOSAddressMSB = 0x03
    _MPOSAddressLSB = 0x04
    _MANGAddressMSB = 0x05
    _MANGAddressLSB = 0x06
    _CONFAddressMSB = 0x07
    _CONFAddressLSB = 0x08
    _RAWANGLEAddressMSB = 0x0C
    _RAWANGLEAddressLSB = 0x0D
    _ANGLEAddressMSB = 0x0E
    _ANGLEAddressLSB = 0x0F
    _STATUSAddress = 0x0B
    _AGCAddress = 0x1A
    _MAGNITUDEAddressMSB = 0x1B
    _MAGNITUDEAddressLSB = 0x1C
    _BURNAddress = 0xFF