#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'gps-interface','console_scripts','gps_pub'
__requires__ = 'gps-interface'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('gps-interface', 'console_scripts', 'gps_pub')()
    )
